US_CITIES = [
    # Top 500 US cities by population
    "New York NY", "Los Angeles CA", "Chicago IL", "Houston TX", "Phoenix AZ",
    "Philadelphia PA", "San Antonio TX", "San Diego CA", "Dallas TX", "San Jose CA",
    "Austin TX", "Jacksonville FL", "Fort Worth TX", "Columbus OH", "Indianapolis IN",
    "Charlotte NC", "San Francisco CA", "Seattle WA", "Denver CO", "Washington DC",
    "Nashville TN", "Oklahoma City OK", "El Paso TX", "Boston MA", "Portland OR",
    "Las Vegas NV", "Memphis TN", "Louisville KY", "Baltimore MD", "Milwaukee WI",
    "Albuquerque NM", "Tucson AZ", "Fresno CA", "Mesa AZ", "Sacramento CA",
    "Atlanta GA", "Kansas City MO", "Colorado Springs CO", "Omaha NE", "Raleigh NC",
    "Virginia Beach VA", "Long Beach CA", "Miami FL", "Oakland CA", "Minneapolis MN",
    "Tulsa OK", "Tampa FL", "Arlington TX", "New Orleans LA", "Wichita KS",
    "Cleveland OH", "Bakersfield CA", "Aurora CO", "Anaheim CA", "Honolulu HI",
    "Santa Ana CA", "Riverside CA", "Corpus Christi TX", "Lexington KY", "Stockton CA",
    "St. Louis MO", "Saint Paul MN", "Henderson NV", "Pittsburgh PA", "Cincinnati OH",
    "Anchorage AK", "Greensboro NC", "Plano TX", "Lincoln NE", "Orlando FL",
    "Irvine CA", "Newark NJ", "Durham NC", "Chula Vista CA", "Toledo OH",
    "Fort Wayne IN", "St. Petersburg FL", "Laredo TX", "Jersey City NJ", "Chandler AZ",
    "Madison WI", "Lubbock TX", "Scottsdale AZ", "Reno NV", "Buffalo NY",
    "Gilbert AZ", "Glendale AZ", "North Las Vegas NV", "Winston-Salem NC", "Chesapeake VA",
    "Norfolk VA", "Fremont CA", "Garland TX", "Irving TX", "Hialeah FL",
    "Richmond VA", "Boise ID", "Spokane WA", "Baton Rouge LA", "Tacoma WA",
    "San Bernardino CA", "Modesto CA", "Fontana CA", "Des Moines IA", "Moreno Valley CA",
    "Santa Clarita CA", "Fayetteville NC", "Birmingham AL", "Oxnard CA", "Rochester NY",
    "Port St. Lucie FL", "Grand Rapids MI", "Huntsville AL", "Salt Lake City UT", "Frisco TX",
    "Yonkers NY", "Amarillo TX", "Glendale CA", "Huntington Beach CA", "McKinney TX",
    "Montgomery AL", "Augusta GA", "Aurora IL", "Akron OH", "Little Rock AR",
    "Tempe AZ", "Columbus GA", "Overland Park KS", "Grand Prairie TX", "Tallahassee FL",
    "Cape Coral FL", "Mobile AL", "Knoxville TN", "Shreveport LA", "Worcester MA",
    "Ontario CA", "Vancouver WA", "Sioux Falls SD", "Chattanooga TN", "Brownsville TX",
    "Fort Lauderdale FL", "Providence RI", "Newport News VA", "Rancho Cucamonga CA", "Santa Rosa CA",
    "Peoria AZ", "Oceanside CA", "Elk Grove CA", "Salem OR", "Pembroke Pines FL",
    "Eugene OR", "Garden Grove CA", "Cary NC", "Corona CA", "Springfield MO",
    "Fort Collins CO", "Jackson MS", "Alexandria VA", "Hayward CA", "Lancaster CA",
    "Lakewood CO", "Clarksville TN", "Palmdale CA", "Salinas CA", "Springfield IL",
    "Hollywood FL", "Pasadena TX", "Sunnyvale CA", "Macon GA", "Kansas City KS",
    "Pomona CA", "Escondido CA", "Savannah GA", "Naperville IL", "Bellevue WA",
    "Joliet IL", "Bridgeport CT", "Rockford IL", "Paterson NJ", "Torrance CA",
    "Killeen TX", "Syracuse NY", "McAllen TX", "Dayton OH", "Miramar FL",
    "Roseville CA", "Thornton CO", "Sterling Heights MI", "Gainesville FL", "Surprise AZ",
    "Denton TX", "Waco TX", "Carrollton TX", "West Valley City UT", "Charleston SC",
    "Warren MI", "Hampton VA", "Columbia SC", "Kent WA", "Visalia CA",
    "Fargo ND", "Olathe KS", "New Haven CT", "Topeka KS", "Thousand Oaks CA",
    "Cedar Rapids IA", "Elizabeth NJ", "Hartford CT", "Concord CA", "Roseville CA",
    "Meridian ID", "Midland TX", "Pearland TX", "Round Rock TX", "Odessa TX",
    "Victorville CA", "Columbia MO", "Athens GA", "Clovis CA", "Palm Bay FL",
    "Murfreesboro TN", "Beaumont TX", "Downey CA", "Costa Mesa CA", "Clearwater FL",
    "West Jordan UT", "Manchester NH", "West Palm Beach FL", "Pueblo CO", "Elgin IL",
    "Arvada CO", "Ann Arbor MI", "Rochester MN", "Gresham OR", "Carlsbad CA",
    "Antioch CA", "Wilmington NC", "North Charleston SC", "High Point NC", "Lowell MA",
    "Peoria IL", "Westminster CO", "Fairfield CA", "Provo UT", "Abilene TX",
    "Vallejo CA", "Evansville IN", "Simi Valley CA", "Stamford CT", "Boulder CO",
    "Broken Arrow OK", "Palm Coast FL", "Lansing MI", "Round Rock TX", "Lewisville TX",
    "Richardson TX", "Lakeland FL", "Allen TX", "College Station TX", "League City TX",
    "Davie FL", "West Covina CA", "Norwalk CA", "Centennial CO", "El Monte CA",
    "Inglewood CA", "Burbank CA", "Temecula CA", "Miami Gardens FL", "Billings MT",
    "Davenport IA", "Wichita Falls TX", "Tyler TX", "Green Bay WI", "Sparks NV",
    "San Marcos CA", "Jurupa Valley CA", "Greeley CO", "Tuscaloosa AL", "Largo FL",
    "South Bend IN", "Edinburg TX", "Pompano Beach FL", "Rialto CA", "Las Cruces NM",
    "Broomfield CO", "Sandy Springs GA", "Leander TX", "South Gate CA", "Daly City CA",
    "Longmont CO", "Boca Raton FL", "San Marcos TX", "Woodbridge NJ", "Champaign IL",
    "Fishers IN", "Plantation FL", "Iowa City IA", "Redmond WA", "Lawton OK",
    "New Braunfels TX", "Hesperia CA", "Kennewick WA", "Avondale AZ", "Nampa ID",
    "Orem UT", "Baytown TX", "Plantation FL", "Sunrise FL", "Spring Hill FL",
    "North Port FL", "Cranston RI", "Appleton WI", "Lynchburg VA", "Lake Charles LA",
    "Somerville MA", "Deltona FL", "Pharr TX", "St. George UT", "Santa Maria CA",
    "Albany NY", "Sugar Land TX", "Dearborn MI", "Springdale AR", "Mission TX",
    "Tracy CA", "Citrus Heights CA", "Hawthorne CA", "Duluth MN", "Alhambra CA",
    "Suffolk VA", "Federal Way WA", "Menifee CA", "Trenton NJ", "Compton CA",
    "Camden NJ", "Yuma AZ", "Chico CA", "Bend OR", "Bloomington IN",
    "Flagstaff AZ", "Conway AR", "Pasco WA", "Bloomington IL", "Eau Claire WI",
    "Asheville NC", "Charlottesville VA", "Rapid City SD", "La Crosse WI", "Missoula MT",
    "State College PA", "Harrisonburg VA", "Burlington VT", "Ithaca NY", "Corvallis OR",
    "Santa Fe NM", "Bozeman MT", "Key West FL", "Sedona AZ", "Savannah GA",
    "Traverse City MI", "Greenville SC", "Pensacola FL", "Galveston TX", "Duluth MN",
    "Santa Cruz CA", "Berkeley CA", "Cambridge MA", "Hoboken NJ", "Pasadena CA",
    "Decatur GA", "Takoma Park MD", "Northampton MA", "Portsmouth NH", "Montpelier VT",
    "Helena MT", "Juneau AK", "Olympia WA", "Pierre SD", "Bismarck ND",
    "Cheyenne WY", "Frankfort KY", "Dover DE", "Annapolis MD", "Jefferson City MO",
    "Carson City NV", "Concord NH", "Trenton NJ", "Harrisburg PA", "Springfield IL",
    "Lansing MI", "Topeka KS", "Lincoln NE", "Baton Rouge LA", "Jackson MS",
    "Montgomery AL", "Tallahassee FL", "Columbia SC", "Raleigh NC", "Richmond VA",
    "Charleston WV", "Augusta ME", "Hartford CT", "Providence RI",
]

